### ISSUE TITLE
TypeError on ThreatActor's to_xml()

### ISSUE THREAD

**Issue by stbe** [STIXProject/python-stix#90]
Hi, I  just bumped into the following problem when setting the "description" property of a ThreatActor object and calling to_xml():

```python
from stix.threat_actor import ThreatActor
from cybox.common import StructuredText
ta = ThreatActor()
ta.description = StructuredText('Test')
print ta.to_xml()
```

```
Traceback (most recent call last):
  File "ta_test.py", line 5, in <module>
    print ta.to_xml()
  File "/tmp/python-stix/stix/base.py", line 50, in to_xml
    self.to_obj().export(s, 0, all_ns_dict, pretty_print=pretty, namespacedef_=namespace_def)
  File "/tmp/python-stix/stix/bindings/threat_actor.py", line 826, in export
    self.exportChildren(outfile, level + 1, nsmap, XML_NS, name_, pretty_print=pretty_print)
  File "/tmp/python-stix/stix/bindings/threat_actor.py", line 854, in exportChildren
    self.Description.export(outfile, level, nsmap, namespace_, name_='Description', pretty_print=pretty_print)
TypeError: export() got multiple values for keyword argument 'name_'
```

Btw., this also happens when setting the "status" property of a campaign object.

**Comment by bworrell** [comment]
I'm not quite sure when I fixed it, but the `Campaign.status` issue was fixed :)

```python
>>> from stix.campaign import Campaign
>>> c = Campaign()
>>> c.status = "Ongoing"
>>> print c.to_xml()
<campaign:Campaign 
	xmlns:cyboxCommon="http://cybox.mitre.org/common-2"
	xmlns:cybox="http://cybox.mitre.org/cybox-2"
	xmlns:cyboxVocabs="http://cybox.mitre.org/default_vocabularies-2"
	xmlns:example="http://example.com"
	xmlns:campaign="http://stix.mitre.org/Campaign-1"
	xmlns:stixCommon="http://stix.mitre.org/common-1"
	xmlns:stixVocabs="http://stix.mitre.org/default_vocabularies-1"
	xmlns:stix="http://stix.mitre.org/stix-1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="
	http://cybox.mitre.org/common-2 http://cybox.mitre.org/XMLSchema/common/2.1/cybox_common.xsd
	http://cybox.mitre.org/cybox-2 http://cybox.mitre.org/XMLSchema/core/2.1/cybox_core.xsd
	http://cybox.mitre.org/default_vocabularies-2 http://cybox.mitre.org/XMLSchema/default_vocabularies/2.1/cybox_default_vocabularies.xsd
	http://stix.mitre.org/Campaign-1 http://stix.mitre.org/XMLSchema/campaign/1.1.1/campaign.xsd
	http://stix.mitre.org/common-1 http://stix.mitre.org/XMLSchema/common/1.1.1/stix_common.xsd
	http://stix.mitre.org/default_vocabularies-1 http://stix.mitre.org/XMLSchema/default_vocabularies/1.1.1/stix_default_vocabularies.xsd
	http://stix.mitre.org/stix-1 http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd" id="example:campaign-43f4510f-6cfa-4587-b705-f196426276ae" timestamp="2015-03-19T02:38:09.645799+00:00" xsi:type='campaign:CampaignType'>
    <campaign:Status xsi:type="stixVocabs:CampaignStatusVocab-1.0">Ongoing</campaign:Status>
</campaign:Campaign>
```

I'm going to close this since it doesn't seem to be an issue any more.
